### ISSUE TITLE
Open SDK does not recognise iFrame by either an id or name 

### ISSUE THREAD

**Issue by Chrys123** [testproject-io/csharp-opensdk#169]
In the previous SDK there was no issue in that part. 

With the same code, the iFrame cannot be recognised in the new SDK.

                Thread.Sleep(5000);
		driver.SwitchTo().Frame("WebResource_DocumentViewer");
		Thread.Sleep(5000);

Error Message:
   OpenQA.Selenium.NoSuchFrameException : No frame element found with name or id DocumentViewer
  Stack Trace:
     at OpenQA.Selenium.Remote.RemoteTargetLocator.Frame(String frameName)
   at TestProject.SDK.Examples.Web.Test.Pages.DynamicsDocumentPage.verifyApplicationData(String registrantPin, String submitterName, String nursingRenewalAnswer, String midwiferyRenewalAnswer, String SCPHNRenewalAnswer, String nursingSCPHNRenewalAnswer, String midwiferySCPHNRenewalAnswer, String revalidateRegistrationAnswer, String nursingHoursAnswer, String currentPracticeAnswer, String practiceLocationAnswer, String employerTypeAnswer, String currentlyPracticingAnswer, String dateFromAnswer, String dateToAnswer, String addressAnswer, String scopeOfPracticeAnswer, String workSettingAnswer, String cpdHoursAnswer, String feedbackAnswer, String reflectiveAccountsAnswer, String reflectiveDiscussionAnswer, String reflectivePinAnswer, String reflectiveTitleAnswer, String reflectiveSurnameAnswer, String reflectiveFirstNameAnswer, String reflectiveEmailAnswer, String reflectivePostcodeAnswer, String reflectiveAddressLineOneAnswer, String reflectiveAddressLineTwoAnswer, String reflectiveAddressLineThreeAnswer, String reflectiveCountryAnswer, String reflectiveConsentAnswer, String healthConditionAnswer, String healthConditionManagementAnswer, String goodCharacterAnswer, String policeChargeAnswer, String regulatoryFindingAnswer, String indemnityCoverAnswer, String indemnityArrangementAnswer, String revalidationDeclarationAnswer, String appraisalConfirmationAnswer, String regularAppraisalAnswer, String NMCLineManagerAnswer, String managerConfirmationAnswer, String managerNMCPINAnswer, String managerTitleAnswer, String managerSurnameAnswer, String managerFirstNameAnswer, String managerEmailAnswer, String managerPostcodeAnswer, String managerReflectiveDiscussionAnswer, String confirmerConsentAnswer, String fullLapseAnswer, String fullRenewAnswer, String nursingAssociateLapsingAnswer, String nursingAssociateLapsingReasonAnswer, String nursingAssociateRequestLapseReasonAnswer, String nursingLapsingReasonAnswer, String midwiferyLapsingReasonAnswer, String SCPHNLapsingReasonAnswer) in C:\Users\ChrysanthiT\Desktop\NMC - Copy\NMC_Online_Automation_Project\NMC_Online_Automation_Project\Web\Test\TestProject.SDK.Examples.Web.Test\Test\RevalidationTests\Pages\DynamicsDocumentPage.cs:line 183
   at TestProject.SDK.Examples.Web.Test.RevalidationTests.RevalidationApplication2021HappyPathTestNurse.revalidationApplicationHappyPathTestNurse() in C:\Users\ChrysanthiT\Desktop\NMC - Copy\NMC_Online_Automation_Project\NMC_Online_Automation_Project\Web\Test\TestProject.SDK.Examples.Web.Test\Test\RevalidationTests\RevalidationTests\RevalidationApplication2021HappyPathTestNurse.cs:line 312

Test Run Failed

**Comment by Chrys123** [comment]
![iFrame](https://user-images.githubusercontent.com/32673876/115384270-5f55ff00-a1c6-11eb-8b12-bd6a20e4eab5.PNG)

**Comment by Chrys123** [comment]
![reportiframe](https://user-images.githubusercontent.com/32673876/115384509-a9d77b80-a1c6-11eb-8050-dfbf71e01d6a.PNG)

**Comment by Rantzur1992** [comment]
Hello @Chrys123 

This Code:

```
            this.driver.Navigate().GoToUrl("https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe");
            this.driver.SwitchTo().Frame("iframeResult");
            var iframe = this.driver.FindElement(By.XPath("//iframe[@title='W3Schools Free Online Web Tutorials']"));
            this.driver.SwitchTo().Frame(iframe);
            this.driver.FindElement(By.Id("w3loginbtn")).Click();
```

Works fine, so I believe it is something in your test.

**Comment by Chrys123** [comment]
No its not, because the same code i sent is used and works in the old SDK, but not the open sdk.
I simply switch to the iframe id, which works still in the old one.

**Comment by Rantzur1992** [comment]
Can you please try the above test and see if it works for you.

**Comment by Chrys123** [comment]
ok it does pass with this var iframe = this.driver.FindElement(By.XPath("//iframe[@title='W3Schools Free Online Web Tutorials']"));
            this.driver.SwitchTo().Frame(iframe); 
But its a little bit like an extra step since it should already get the frame id from the switch method,

Thanks anyway

**Comment by Chrys123** [comment]
driver.SwitchTo().Frame(this.driver.FindElement(this.documentIFrame));

**Comment by Rantzur1992** [comment]
`this.driver.SwitchTo().Frame("iframeResult");`

Did work for me, perhaps it just times out quicker searching for the iFrame
