### ISSUE TITLE
Agent failed with 500 error code when colon is passed to driver

### ISSUE THREAD

**Issue by SantoshYakkala** [testproject-io/csharp-opensdk#234]
public static string datetime = DateTime.Now.ToString();
public ChromeDriver driver = new(token: DevToken,reportName:"Test-1" + datetime, reportPath:"C:\\Share");

TestProject.OpenSDK.Exceptions.AgentConnectException
  HResult=0x80131500
  Message=Agent responsed with status code 500: [Illegal char <:> at index 27: C:\Share\Test-115/07/2021 1:07:29 AM.html]
  Source=TestProject.OpenSDK
  StackTrace:
   at TestProject.OpenSDK.Internal.Rest.AgentClient.HandleSessionStartFailure(IRestResponse startSessionResponse)
   at TestProject.OpenSDK.Internal.Rest.AgentClient.StartSession(ReportSettings reportSettings, DriverOptions capabilities)
   at TestProject.OpenSDK.Internal.Rest.AgentClient..ctor(Uri remoteAddress, String token, DriverOptions capabilities, ReportSettings reportSettings, Boolean disableReports, Version compatibleVersion)
   at TestProject.OpenSDK.Internal.Rest.AgentClient.GetInstance(Uri remoteAddress, String token, DriverOptions capabilities, ReportSettings reportSettings, Boolean disableReports, Version compatibleVersion)
   at TestProject.OpenSDK.Drivers.BaseDriver..ctor(Uri remoteAddress, String token, DriverOptions driverOptions, String projectName, String jobName, Boolean disableReports, ReportType reportType, String reportName, String reportPath, Nullable`1 remoteConnectionTimeout)
   at TestProject.OpenSDK.Drivers.Web.ChromeDriver..ctor(Uri remoteAddress, String token, ChromeOptions chromeOptions, String projectName, String jobName, Boolean disableReports, ReportType reportType, String reportName, String reportPath, Nullable`1 remoteConnectionTimeout)
   at TestProject1.UnitTest1..ctor() in C:\Users\Viswa\source\repos\TestProject1\UnitTest1.cs:line 14

**Comment by s-glatshtein** [comment]
So the colon is clearly an illegal character.
@mstrelex I think agent should sanitize the file name, since it returns the path it saves in

**Comment by mstrelex** [comment]
Agree

**Comment by s-glatshtein** [comment]
Hi @SantoshYakkala 
I'd like to update you that a fix for this issue will be implemented in the upcoming agent version that should be released next week. I am closing this bug. If once agent 3.2.0 is released the problem returns, please feel free to contact us again.

**Comment by CustomerSuccessTP** [comment]
Hi,
We have released agent 3.2.0 and it's available now here:
https://app.testproject.io/#/download
Let us know if you encounter the issue again.
